### ISSUE TITLE
set-current-color does not apply to paths with default fill

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [matafokka/vite-awesome-svg-loader#1]
The [fill attribute](https://www.w3.org/TR/SVG2/painting.html#FillProperties) defaults to "black" if it's not specified, but the `set-current-color` does not appear to set `fill="currentColor"` if the attribute is missing, causing the paths to appear black.

The ionicons set in particular does not have fills specified on most of its paths.

**Comment by matafokka** [comment]
Hello, thanks for reporting this! New 1.3.3 release is on the way, should be on npm in like 10 minutes. [As per MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill), I've also fixed same issue for following elements:

1. `<circle>`
1. `<ellipse>`
1. `<path>`
1. `<polygon>`
1. `<polyline>`
1. `<rect>`
1. `<text>`
1. `<textPath>`
1. `<tref>`
1. `<tspan>`
