### ISSUE TITLE
Constant "Empty string passed to getElementById()" warnings

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [matafokka/vite-awesome-svg-loader#2]
Seems like every time an `SvgImage` is rendered, there is a `Empty string passed to getElementById()` warning emitted in Firefox. This happens in my own project as well as the demo page on https://matafokka.github.io/vite-awesome-svg-loader/react-demo/ .

It does not appear to affect functionality but it crowds the console.

I'd diagnose it further but I'm unable to get vite or the browser to load source maps for my dependencies, so I can't debug the unobfuscated Javascript.

**Comment by matafokka** [comment]
Hello again! Thanks for reporting this. New 1.3.4 release is on its way. I just fixed the warnings, but I believe there's an issue with the React integration itself since other demos don't seem to pass empty IDs. I'll take a look tomorrow or at the end of this week.

**Comment by matafokka** [comment]
Hello! I fixed the underlying problems. `SvgImage` would try to unmount on SVG source code changes. I also didn't track actual element ID. Sorry, my React skills are a bit rusty.

It's all fixed now, please update to version 1.3.5.
